# -*- coding: utf-8 -*-
"""personal_rag_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n_nY1bmLayLlkkfY_W318eVFmo95XbJh
"""

!pip uninstall -y numpy
!pip install numpy==1.26.4 --force-reinstall

!pip install -q \
langchain==0.2.14 \
langchain-core==0.2.32 \
langchain-community==0.2.12 \
faiss-cpu \
pypdf

!pip install -U langchain-huggingface sentence-transformers

!pip install google-genai

import os
import google.genai as genai

# The 'configure' method is not directly available on the 'google.generativeai' module.
# The recommended way to set the API key is via an environment variable.
os.environ["GOOGLE_API_KEY"] = "AIzaSyAzY3f3mdf0rYgPr2tyDN7z-TaXYmSbRAk"

from google.colab import files
uploaded = files.upload()

from langchain_community.document_loaders import PyPDFLoader, TextLoader

documents = []

documents.extend(PyPDFLoader("Jubin_Full_Resume.pdf").load())
documents.extend(TextLoader("projects.txt").load())

print("Loaded docs:", len(documents))

from langchain.text_splitter import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=250
)

docs = splitter.split_documents(documents)

print("Chunks:", len(docs))

from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

from langchain_community.vectorstores import FAISS

vectorstore = FAISS.from_documents(docs, embeddings)

print("Vector DB ready!")

from google import genai
from google.genai import types  # ← import this for GenerateContentConfig

# Client creation (do this once, outside the function)
client = genai.Client(api_key="AIzaSyDE7aT-H9B2465oKbIR8ExHxcnMlv3ZFHE")  # or env var

def ask_rag(query: str) -> str:
    docs = vectorstore.similarity_search(query, k=10)

    context = "\n\n".join([d.page_content for d in docs])

    prompt = f"""You are an expert career advisor answering questions about the candidate's CV.

**Primary source**: Use ONLY the CV context below for all facts about the candidate's experience, skills, education, projects, etc.
**External references**: For deeper insights (industry trends, company background, project impact, verification of achievements, latest news, or comparisons), automatically use the Google Search tool to fetch real-time external information.

Rules:
- Always ground answers in the CV first.
- If the CV doesn't have enough detail for a "deep" answer, use Google Search to enrich it.
- When using external info, briefly mention the source (e.g., "According to recent industry reports...").
- If you truly don't know, say: "I don't know based on the provided CV and available references."
Context (excerpts from the CV):
{context}

Question:
{query}
""".strip()

    # Use 'config' instead of 'generation_config'
    response = client.models.generate_content(
        model="gemini-2.5-flash",  # or "gemini-2.5-pro", "gemini-flash-latest"
        contents=prompt,

        config=types.GenerateContentConfig(   # ← this is the correct argument name
            temperature=0.8,                  # low for factual RAG
            max_output_tokens=400,
            top_p=0.95,
            tools=[types.Tool(google_search=types.GoogleSearch())],
            # top_k=40,                       # optional
            # stop_sequences=["\n\n"],        # optional
            # candidate_count=1,              # default anyway
        ),

        # Optional: safety_settings=types.SafetySettingsDict({...})
    )

    return response.text

while True:
    q = input("\nAsk (type 'exit'): ")

    if q.lower() == "exit":
        break

    print("\nAnswer:\n", ask_rag(q))

